export enum MovieSubTypes {
  AccountStates = 'account_states',
  AlternativeTitles = 'alternative_titles',
  Changes = 'changes',
  Credits = 'credits',
  ExternalIds = 'external_ids',
  Images = 'images',
  Keywords = 'keywords',
  Latest = 'latest',
  Lists = 'lists',
  Recommendations = 'recommendations',
  ReleaseDates = 'release_dates',
  Reviews = 'reviews',
  Similar = 'similar',
  Translations = 'translations',
  Videos = 'videos',
  WatchProviders = 'watch/providers',
}
